apiVersion: v1
kind: Pod
metadata:
  name: web-nodeport
  labels:
    type: web-app-nodeport

spec:
  containers:
    - name: web-server-apache
      image: httpd
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service-nodeport

spec:
  type: NodePort
  selector:
    type: web-app-nodeport
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30008